In [9]:
import os, sys
import numpy as np
import pandas as pd
from typing import Dict
from sklearn.ensemble import IsolationForest

In [2]:
print(os.getcwd())

/home/mila/teaching/user09

In [3]:
path_to_images = "/home/mila/teaching/user09/new_data/Train/Image/"
path_to_profile = "/home/mila/teaching/user09/new_data/Train/Profile/"
path_to_text = "/home/mila/teaching/user09/new_data/Train/Text/"

sys.path.append(path_to_images)
sys.path.append(path_to_profile)
sys.path.append(path_to_text)

print(sys.path)

['/home/mila/teaching/user09', '/home/mila/teaching/user09/.conda/envs/fb-env/lib/python37.zip', '/home/mila/teaching/user09/.conda/envs/fb-env/lib/python3.7', '/home/mila/teaching/user09/.conda/envs/fb-env/lib/python3.7/lib-dynload', '', '/home/mila/teaching/user09/.conda/envs/fb-env/lib/python3.7/site-packages', '/home/mila/teaching/user09/.conda/envs/fb-env/lib/python3.7/site-packages/IPython/extensions', '/home/mila/teaching/user09/.ipython', '/home/mila/teaching/user09/new_data/Train/Image/', '/home/mila/teaching/user09/new_data/Train/Profile/', '/home/mila/teaching/user09/new_data/Train/Text/']

In [6]:
liwc_df = pd.read_csv(path_to_text + "liwc.csv")
nrc_df = pd.read_csv(path_to_text + "nrc.csv")

### Outlier detection with LIWC

In [8]:
liwc_df.head(n=2)

,userId,WC,WPS,Sixltr,Dic,Numerals,funct,pronoun,ppron,i,...,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP,AllPct
0,1c1bb692d7765344d418c0247962e7f8,156,17.33,25.00,76.92,1.92,45.51,9.62,6.41,3.21,...,1.92,0.0,5.77,5.77,2.56,0.0,2.56,0.64,5.13,70.51
1,2eba17f4ec950f23af8d31a1d1db4518,176,11.00,21.02,84.66,0.00,53.41,15.34,12.50,7.39,...,0.57,0.0,0.00,13.07,0.00,0.0,2.27,0.28,1.14,39.77

In [10]:
rng = np.random.RandomState(42)
clf = IsolationForest(max_samples=100, random_state=rng, behaviour="new", contamination=.1)

In [11]:
X_train_liwc = liwc_df.values[:, 1:]
X_train_nrc = nrc_df.values[:, 1:]

In [12]:
clf.fit(X_train_liwc)
y_pred_train = clf.predict(X_train_liwc)

In [13]:
liwc_outliers = liwc_df[np.where(y_pred_train == -1, True, False)]

In [14]:
print('There are {} outliers in the liwc dataset.'.format(len(liwc_outliers)))
liwc_outliers.head(n=5)

There are 950 outliers in the liwc dataset.

,userId,WC,WPS,Sixltr,Dic,Numerals,funct,pronoun,ppron,i,...,Colon,SemiC,QMark,Exclam,Dash,Quote,Apostro,Parenth,OtherP,AllPct
4,5ca01e48cdf661e932cfe58588360a7f,18,18.00,44.44,55.56,0.00,27.78,0.00,0.00,0.00,...,22.22,0.00,3661.11,0.00,0.00,11.11,0.00,5.56,16.67,4111.11
12,740aa055e9dccaee874ab7ec7e499d8e,45,22.50,26.67,84.44,0.00,62.22,22.22,13.33,13.33,...,0.00,0.00,0.00,0.00,4.44,0.00,6.67,0.00,4.44,26.67
19,a323427e0712816a342e47f64717d8c5,186,26.57,9.68,84.41,1.08,51.08,27.42,26.34,12.37,...,3.23,0.00,2.15,5.38,1.61,0.54,3.23,9.95,11.29,58.60
24,b224aa9db776de8653279a1be1cd6a44,157,22.43,20.38,83.44,0.64,29.94,10.19,6.37,2.55,...,3.82,0.64,1.91,8.92,6.37,0.64,0.00,1.91,6.37,71.34
25,bfd70ee36193fc0659fc5b5faff05326,125,3.91,25.60,56.00,0.00,27.20,7.20,6.40,2.40,...,5.60,0.00,1.60,6.40,4.80,0.80,8.00,3.60,12.00,177.60

### Outlier detection with NRC

In [15]:
clf.fit(X_train_nrc)
y_pred_train = clf.predict(X_train_nrc)

In [16]:
nrc_outliers = nrc_df[np.where(y_pred_train == -1, True, False)]

In [17]:
print('There are {} outliers in the nrc dataset.'.format(len(nrc_outliers)))
nrc_outliers.head(n=5)

There are 950 outliers in the nrc dataset.

,userId,positive,negative,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
4,001494c3b74f124a2e3435fff17f376b,0.875000,0.125000,0.019231,0.134615,0.019231,0.019231,0.384615,0.019231,0.057692,0.346154
16,00404121e4d850fe18747a5283461132,0.600000,0.400000,0.000000,0.000000,0.000000,0.200000,0.400000,0.000000,0.400000,0.000000
21,00538b480bf5c5965f8cade49650a0cf,0.371429,0.628571,0.194805,0.038961,0.025974,0.194805,0.077922,0.207792,0.207792,0.051948
23,005cc9cec5f370b3465cef396e9e236e,0.666667,0.333333,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.500000
32,0080bd1c13acc3b6601c6fa31c7acfcf,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000